config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  require 'sidekiq/web'
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq', as: :sidekiq

    namespace :admin do
      # TODO: administrate
    end

    namespace :manage do
      resources :fragments
      resources :render_templates do
        get 'editor', on: :member
        get 'preview', on: :member
      end
      resources :documents do
        get 'preview', on: :member
        get 'download', on: :member
      end
      root to: 'dashboard#index'
    end
  end

  resources :documents, only: %i[show retry create] do
    post 'retry', on: :member
  end

  get 'playground', to: 'welcome#playground'
  get 'iframe', to: 'welcome#iframe'

  root 'welcome#index'
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!

  def index; end

  def iframe
    contract_number = params[:contract_id]
    # TODO: remove after demo!
    @token = User.last.api_token

    template = RenderTemplate.where(name: 'local-kh-pdf1').order(:updated_at).last
    @template = template.name
    @version = template.version

    @data = {
      contract_number: contract_number,
      first_name: 'SCIP',
      last_name: 'Customer'
    }

    response.headers.except! 'X-Frame-Options'
    response.headers['X-Permitted-Cross-Domain-Policies'] = 'all'

    render layout: nil
  end

  def playground
    @document = Document.new

    @sample_templates = RenderTemplate.last(5).map do |template|
      {
        name: template.name,
        version: template.version,
        schema: template.schema.to_json
      }
    end
  end
end

app/helpers/welcome_helper.rb
# frozen_string_literal: true

module WelcomeHelper
end

app/views/welcome/iframe.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Pretty.ink</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= action_cable_meta_tag %>

  <%#= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  <%#= stylesheet_pack_tag 'application-styles', media: 'all', 'data-turbolinks-track': 'reload' %>

  <%= javascript_pack_tag 'application-scripts', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag 'application-scripts', 'data-turbolinks-track': 'reload' %>


<style>
.btn {
background-attachment:scroll;
background-clip:border-box;
background-color:rgb(255, 255, 255);
background-image:none;
background-origin:padding-box;
background-position-x:0%;
background-position-y:0%;
background-size:auto;
border-bottom-color:rgb(212, 212, 212);
border-bottom-left-radius:3px;
border-bottom-right-radius:3px;
border-bottom-style:solid;
border-bottom-width:1px;
border-image-outset:0;
border-image-repeat:stretch;
border-image-slice:100%;
border-image-source:none;
border-image-width:1;
border-left-color:rgb(212, 212, 212);
border-left-style:solid;
border-left-width:1px;
border-right-color:rgb(212, 212, 212);
border-right-style:solid;
border-right-width:1px;
border-top-color:rgb(212, 212, 212);
border-top-left-radius:3px;
border-top-right-radius:3px;
border-top-style:solid;
border-top-width:1px;
box-sizing:border-box;
color:rgb(51, 51, 51);
cursor:pointer;
display:inline-block;
font-family:"PT Sans", arial, sans-serif;
font-size:16px;
font-stretch:100%;
font-style:normal;
font-variant-caps:normal;
font-variant-east-asian:normal;
font-variant-ligatures:normal;
font-variant-numeric:normal;
font-weight:400;
line-height:32px;
margin-bottom:0px;
margin-left:0px;
margin-right:8px;
margin-top:0px;
padding-bottom:0px;
padding-left:19px;
padding-right:19px;
padding-top:0px;
text-decoration-color:rgb(51, 51, 51);
text-decoration-line:none;
text-decoration-style:solid;
vertical-align:baseline;

}
</style>
</head>

<body class="" style="margin: 0; padding: 0">
  <div data-behavior="vue">
    
<% if params[:debug] %>
  @token: <%= @token %>" <br />
  @template: <%= @template %> <br />
  @version: <%= @version %> <br />
  @data: <%= @data.to_json %>

  <br />
<% end %>

    <%# @document = Document.last %>

    <raw-create-button 
    :initial-document-id="'<%= @document&.id %>'" 
    :initial-document-state="'<%= @document&.aasm_state %>'" 

    :initial-token="'<%= @token %>'"
    :initial-template="'<%= @template %>'"
    :initial-version="'<%= @version %>'"
    :initial-data="<%= @data.to_json %>"
    ></raw-create-button> 



  </div>
</body>

</html>

app/views/welcome/index.html.erb
<% content_for :title do %>
  Welcome
<% end %>

<%= render 'pages/center_panel' do %>

  <p>
    This is the document rendering service of Pairing.sh.
  </p>

  <p>
    In the future you will see a marketing page here, with pricing, contract, trial etc.
  </p>

  <p>
    If you have a login:  <%= link_to 'click here', manage_root_path, class: 'btn btn-primary btn-sm'%>
  </p>


  <p>
    If you want to know what this is about, ask Till from
    <a href="https://pairing.sh">Pairing.sh</a>
  </p>

<% end %>

app/views/welcome/playground.html.erb
<p id="notice"><%= notice %></p>

<h1 class='mb-4'>API Playground</h1>


<playground-create-document 
  :sample-templates="<%= @sample_templates.to_json %>"
  initial-token="<%= current_user&.api_token %>">
</playground-create-document>


<hr class='mt-5 mb-5' />


<playground-get-status
  initial-token="<%= current_user&.api_token %>">
</playground-get-status>


<%
=begin%>
 
<h2>Preview 
  <i class="fas fa-external-link-alt"></i>
</h2>

<div class="card">
  <div class="card-body">
    ...

  </div>
</div> 
<%
=end%>