config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  require 'sidekiq/web'
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq', as: :sidekiq

    namespace :admin do
      # TODO: administrate
    end

    namespace :manage do
      resources :fragments
      resources :render_templates do
        get 'editor', on: :member
        get 'preview', on: :member
      end
      resources :documents do
        get 'preview', on: :member
        get 'download', on: :member
      end
      root to: 'dashboard#index'
    end
  end

  resources :documents, only: %i[show retry create] do
    post 'retry', on: :member
  end

  get 'playground', to: 'welcome#playground'
  get 'iframe', to: 'welcome#iframe'

  root 'welcome#index'
end

app/views/layouts/_alerts.html.erb
<% if alert %>
  <div class="alert alert-warning" role="alert">
    <%= alert %></p>
  </div>
<% end %>

<% if notice %>
<div class="alert alert-info" role="alert">
  <%= notice %>
</div>
<% end %>

app/views/layouts/_breadcrumbs.html.erb
<%
  @render_template ||= nil
  @fragment ||= nil

  if @fragment && @fragment.render_template
    @render_template = @fragment.render_template 
  end

  if @render_template
    @secondary = ["Templates", 
      manage_render_templates_path
    ]

    @tertiary = [@render_template.name, 
      [:manage, @render_template]
    ]

  end

  @secondary ||= [controller_name, manage_root_path]
%>

<div class="content-breadcrumbs">
  <div class="container">
    <div class="row mb-2">
      <div class="col-sm-6">
        
      </div><!-- /.col -->
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <% unless ['welcome'].include?(controller_name) %>
            <li class="breadcrumb-item">
              <%= link_to 'Manage', manage_root_path %>
            </li>
          <% end %>

          <li class="breadcrumb-item">
            <%= link_to @secondary.first, @secondary.second %>
          </li>

          <% if @tertiary %>
          <li class="breadcrumb-item">
            <%= link_to @tertiary.first, @tertiary.second %>
          </li>
          <% end %>

          <li class="breadcrumb-item active"><%= action_name %></li>
        </ol>
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
  </div>

app/views/layouts/_footer.html.erb
<%
=begin%>
<footer class="main-footer">
  <div class="container">
    © 2020 Maerketing Europe OÜ | Sakala 7-2, 10141 Tallinn, Estonia | info@pairing.sh
  </div>
</footer>
<%
=end%>

<div class='footer-wrapper'>
<footer class="container py-5">
  <div class="row">
    <div class="col-12 col-md">
      <%= image_pack_tag "logo.svg", class: 'img-fluid mr-2', style: 'height: 20px' %>
      Pretty.ink
            
      <small class="d-block text-muted mt-3">
      © 2020 Maerketing Europe OÜ | Sakala 7-2, 10141 Tallinn, Estonia | info@pairing.sh
      </small>
      <br />
      <small class="d-block mb-3 text-muted ">
        <%= deployment_info %>
      </small>
    </div>
    <div class="col-6 col-md">
      <h5>Features</h5>
      <ul class="list-unstyled text-small">
        <li><a class="text-muted" href="#">Cool stuff</a></li>
        <li><a class="text-muted" href="#">Random feature</a></li>
        <li><a class="text-muted" href="#">Team feature</a></li>
        <li><a class="text-muted" href="#">Stuff for developers</a></li>
        <li><a class="text-muted" href="#">Another one</a></li>
        <li><a class="text-muted" href="#">Last time</a></li>
      </ul>
    </div>
    <div class="col-6 col-md">
      <h5>Resources</h5>
      <ul class="list-unstyled text-small">
        <li><a class="text-muted" href="#">Resource</a></li>
        <li><a class="text-muted" href="#">Resource name</a></li>
        <li><a class="text-muted" href="#">Another resource</a></li>
        <li><a class="text-muted" href="#">Final resource</a></li>
      </ul>
    </div>
    <div class="col-6 col-md">
      <h5>Resources</h5>
      <ul class="list-unstyled text-small">
        <li><a class="text-muted" href="#">Business</a></li>
        <li><a class="text-muted" href="#">Education</a></li>
        <li><a class="text-muted" href="#">Government</a></li>
        <li><a class="text-muted" href="#">Gaming</a></li>
      </ul>
    </div>
    <div class="col-6 col-md">
      <h5>About</h5>
      <ul class="list-unstyled text-small">
        <li><a class="text-muted" href="#">Team</a></li>
        <li><a class="text-muted" href="#">Locations</a></li>
        <li><a class="text-muted" href="#">Privacy</a></li>
        <li><a class="text-muted" href="#">Terms</a></li>
      </ul>
    </div>
  </div>
</footer>
  </div>

app/views/layouts/_header.html.erb
<nav class="main-header navbar navbar-expand navbar-white navbar-light border-bottom">
  <%= image_pack_tag "logo.svg", class: 'img-fluid mr-2', style: 'height: 20px' %>
  
  <% if current_user&.admin? %>
    <%= link_to 'Pretty.ink', manage_root_path, class: 'navbar-brand' %>
  <% else %>
    <%= link_to 'Pretty.ink', root_path, class: 'navbar-brand' %>
  <% end %>


  <!-- Left navbar links -->
  <ul class="navbar-nav">
    <% if current_user&.admin? %>
      <li class="nav-item d-none d-sm-inline-block">
        <%= link_to manage_render_templates_path, class: "nav-link" do %>
          <i class="fas fa-clone"></i> Templates
        <% end %>
      </li>

      <li class="nav-item d-none d-sm-inline-block">
        <%= link_to manage_documents_path, class: "nav-link" do %>
          <i class="fas fa-file"></i> Documents
        <% end %>
      </li>
    <% end %>

    <li class="nav-item d-none d-sm-inline-block">
      <%= link_to 'API Playground', playground_path, class: "nav-link" %>
    </li>

  </ul>
  
  <!-- SEARCH FORM -->
  <%# <form class="form-inline ml-3">
    <div class="input-group input-group-sm">
      <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
      <div class="input-group-append">
        <button class="btn btn-navbar" type="submit">
          <i class="fas fa-search"></i>
        </button>
      </div>
    </div>
  </form> %>
  
  <!-- Right navbar links -->
  <ul class="navbar-nav ml-auto">


    <li class="nav-item d-none d-sm-inline-block">
      <%= link_to root_path, class: "nav-link" do %>
        <i class="fas fa-wrench"></i>
      <% end %>
    </li>

    <li class="nav-item d-none d-sm-inline-block">
      <%= link_to sidekiq_path, class: "nav-link" do %>
        <i class="fas fa-thermometer-quarter"></i>
      <% end %>
    </li>

    <li class="nav-item d-none d-sm-inline-block">
      <%= link_to root_path, class: "nav-link" do %>
        <i class="fas fa-user-cog"></i>
      <% end %>
    </li>


    <%# 
    profile settings?
    
    <li class="nav-item">
      <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#"><i class="fas fa-th-large"></i></a>
    </li> %>


  </ul>
</nav>

app/views/layouts/_sidebar.html.erb
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
  <a href="index3.html" class="brand-link">
    <span class="brand-text font-weight-light">Standup App</span>
  </a><!-- Sidebar -->
  <div class="slimScrollDiv" style="position: relative; overflow: hidden; width: auto; height: 652px;"><div class="sidebar" style="min-height: 652px; overflow: hidden; width: auto; height: 652px;">
    <!-- Sidebar user panel (optional) -->
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
      <div class="image">
        <img src="http://placehold.it/160x160" class="img-circle elevation-2" alt="User Image">
      </div>
      <div class="info">
        <a href="#" class="d-block">User Name</a>
      </div>
    </div><!-- Sidebar Menu -->
    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <!-- Add icons to the links using the .nav-icon class
             with font-awesome or any other icon font library -->
        <li class="nav-item has-treeview menu-open">
          <a href="#" class="nav-link active">
            <i class="nav-icon fas fa-tachometer-alt"></i>
            <p>
              Activity
              <i class="right fas fa-angle-left"></i>
            </p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href="./index.html" class="nav-link active">
                <i class="far fa-circle nav-icon"></i>
                <p>Mine</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="./index2.html" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Feed</p>
              </a>
            </li>
          </ul>
        </li>
      </ul>
    </nav>
    <!-- /.sidebar-menu -->
  </div>
  <!-- /.sidebar -->
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Pretty.ink</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= action_cable_meta_tag %>

  <%#= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  <%= stylesheet_pack_tag 'application-styles', media: 'all', 'data-turbolinks-track': 'reload' %>

  <%= javascript_pack_tag 'application-scripts', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag 'application-scripts', 'data-turbolinks-track': 'reload' %>


</head>

<body class="application hold-transition sidebar-collapse layout-top-nav">
  <div data-behavior="vue">
    <div class="wrapper">
      <div class="container">
        <%= render partial: "layouts/header" %>
      </div>
      <div class="own-content-wrapper">
        <div class="container">

          <%= render partial: "layouts/alerts" %>
          <%= render partial: "layouts/breadcrumbs" %>

          <%= yield %>
        </div>
      </div>
      <%= render partial: "layouts/footer" %>
    </div>
  </div>
</body>

</html>

app/views/layouts/editor.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Pretty.ink</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= action_cable_meta_tag %>

  <%#= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  <%= stylesheet_pack_tag 'application-styles', media: 'all', 'data-turbolinks-track': 'reload' %>

  <%= javascript_pack_tag 'application-scripts', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag 'application-scripts', 'data-turbolinks-track': 'reload' %>


</head>

<body class="editor">
  <div data-behavior="vueESC">

    <%= yield %>
    
  </div>
</body>

</html>

app/views/layouts/iframe.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Pretty.ink</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= action_cable_meta_tag %>

  <%#= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  <%= stylesheet_pack_tag 'application-styles', media: 'all', 'data-turbolinks-track': 'reload' %>

  <%= javascript_pack_tag 'application-scripts', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag 'application-scripts', 'data-turbolinks-track': 'reload' %>


</head>

<body class="application hold-transition sidebar-collapse layout-top-nav">
  <div data-behavior="vue">
    <div class="wrapper">
      <div class="container">
        <%= render partial: "layouts/header" %>
      </div>
      <div class="own-content-wrapper">
        <div class="container">

          <%= render partial: "layouts/alerts" %>
          <%= render partial: "layouts/breadcrumbs" %>

          <%= yield %>
        </div>
      </div>
    </div>
  </div>
</body>

</html>